name: Make PyPI Release

on:
  workflow_run:
    workflows: ["Python Tests"]
    types: [completed]
  workflow_dispatch:
  release:
    types: [published, released]

permissions:
  contents: read

jobs:
  check-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    outputs:
      should_publish: ${{ steps.check.outputs.should_publish }}
      url: ${{ steps.check.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.11'

      - name: Cache, pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-a-dee-doo-dah
          restore-keys: pip-a-dee-doo-dah
      - run: pip install build

      - name: Check if version exists on PyPI
        id: check
        run: |
          python -c "
          import os, pathlib, tomllib, urllib.error, urllib.request

          dictionaryProject = tomllib.loads(pathlib.Path('pyproject.toml').read_text())['project']
          versionPackage, namePackage = dictionaryProject['version'], dictionaryProject['name']
          url = f'https://pypi.org/project/{namePackage}/{versionPackage}'

          try:
              urllib.request.urlopen(urllib.request.Request(url, method='HEAD'))
          except urllib.error.HTTPError as HTTPError:
              if HTTPError.code == 404:
                  with open(os.environ['GITHUB_OUTPUT'], 'a') as appendStream:
                      appendStream.write('should_publish=true\n')
                      appendStream.write(f'url={url}\n')
          "

      - name: Build wheels and source dist
        if: steps.check.outputs.should_publish == 'true'
        run: python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    needs: [check-version]
    if: needs.check-version.outputs.should_publish == 'true'
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: ${{ needs.check-version.outputs.url }}
    permissions:
      id-token: write
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc #v1.12.2
        with:
          packages-dir: dist/
